const express = require('express');
const router = express.Router();
const { protect, authorize, supplierFilter } = require('../middleware/auth');
const PurchaseOrder = require('../models/PurchaseOrder');
const InventorySnapshot = require('../models/InventorySnapshot');

// GET /api/purchase-orders
router.get('/', protect, supplierFilter, async (req, res) => {
  try {
    const filter = {};
    if (req.supplierFilter)    filter.supplier = req.supplierFilter;
    if (req.query.status)      filter.status   = req.query.status;
    if (req.query.supplier)    filter.supplier  = req.query.supplier.toUpperCase();
    if (req.query.asin)        filter.asin      = req.query.asin;

    const pos = await PurchaseOrder.find(filter)
      .populate('confirmedBy', 'name')
      .populate('approvedBy',  'name')
      .populate('deliveredBy', 'name')
      .sort({ createdAt: -1 })
      .limit(200);

    res.json({ purchaseOrders: pos, total: pos.length });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/purchase-orders  — create PO (system suggestion)
router.post('/', protect, authorize('admin'), async (req, res) => {
  try {
    const { asin, quantity } = req.body;

    // Get context from latest snapshot
    const snapshot = await InventorySnapshot.findOne().sort({ createdAt: -1 });
    let context = {};
    if (snapshot) {
      const row = snapshot.rows.find(r => r.asin === asin);
      if (row) {
        context = {
          companyDocAtCreation: row.companyDOC,
          whDocAtCreation:      row.whDOC,
          drrAtCreation:        row.totalDRR,
          suggestQty:           row.suggestQty,
          ean:                  row.ean,
          sku:                  row.sku,
          title:                row.title,
          supplier:             row.supplier
        };
      }
    }

    const po = await PurchaseOrder.create({
      asin, quantity,
      ...context,
      statusHistory: [{ status: 'system_suggested', note: 'Auto-generated by system' }]
    });

    res.status(201).json({ purchaseOrder: po });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /api/purchase-orders/:id/confirm  — supplier confirms
router.patch('/:id/confirm', protect, authorize('admin', 'china_supplier', 'md_supplier'), async (req, res) => {
  try {
    const po = await PurchaseOrder.findById(req.params.id);
    if (!po) return res.status(404).json({ error: 'PO not found' });

    // Supplier can only confirm their own supplier POs
    if (req.user.role === 'china_supplier' && po.supplier !== 'CHINA')
      return res.status(403).json({ error: 'Access denied' });
    if (req.user.role === 'md_supplier' && po.supplier !== 'MD')
      return res.status(403).json({ error: 'Access denied' });

    if (po.status !== 'system_suggested')
      return res.status(400).json({ error: `Cannot confirm PO with status: ${po.status}` });

    po.status = 'supplier_confirmed';
    po.supplierConfirmedAt = new Date();
    po.confirmedBy = req.user._id;
    po.supplierNotes = req.body.notes || '';
    po.statusHistory.push({ status: 'supplier_confirmed', changedBy: req.user._id, note: req.body.notes });

    await po.save();
    res.json({ purchaseOrder: po, message: 'PO confirmed by supplier' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /api/purchase-orders/:id/approve  — admin approves
router.patch('/:id/approve', protect, authorize('admin'), async (req, res) => {
  try {
    const po = await PurchaseOrder.findById(req.params.id);
    if (!po) return res.status(404).json({ error: 'PO not found' });
    if (po.status !== 'supplier_confirmed')
      return res.status(400).json({ error: 'PO must be supplier_confirmed before approval' });

    po.status = 'admin_approved';
    po.adminApprovedAt = new Date();
    po.approvedBy = req.user._id;
    po.adminNotes = req.body.notes || '';
    po.statusHistory.push({ status: 'admin_approved', changedBy: req.user._id, note: req.body.notes });

    await po.save();
    res.json({ purchaseOrder: po, message: 'PO approved by admin' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /api/purchase-orders/:id/reject  — admin rejects
router.patch('/:id/reject', protect, authorize('admin'), async (req, res) => {
  try {
    const po = await PurchaseOrder.findById(req.params.id);
    if (!po) return res.status(404).json({ error: 'PO not found' });

    po.status = 'rejected';
    po.adminNotes = req.body.reason || 'Rejected by admin';
    po.statusHistory.push({ status: 'rejected', changedBy: req.user._id, note: req.body.reason });

    await po.save();
    res.json({ purchaseOrder: po, message: 'PO rejected' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /api/purchase-orders/:id/deliver  — admin marks delivered
router.patch('/:id/deliver', protect, authorize('admin'), async (req, res) => {
  try {
    const po = await PurchaseOrder.findById(req.params.id);
    if (!po) return res.status(404).json({ error: 'PO not found' });

    const { status, discrepancyNotes } = req.body; // 'delivered' or 'discrepancy'
    po.status = status === 'discrepancy' ? 'delivered' : 'delivered';
    po.deliveredAt = new Date();
    po.deliveredBy = req.user._id;
    po.discrepancyNotes = discrepancyNotes || '';
    po.statusHistory.push({ status: 'delivered', changedBy: req.user._id, note: discrepancyNotes || 'Delivered' });

    await po.save();
    res.json({ purchaseOrder: po, message: 'PO marked as delivered' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/purchase-orders/stats  — PO counts by status/supplier
router.get('/stats', protect, supplierFilter, async (req, res) => {
  try {
    const matchFilter = req.supplierFilter ? { supplier: req.supplierFilter } : {};
    const stats = await PurchaseOrder.aggregate([
      { $match: matchFilter },
      { $group: { _id: { status: '$status', supplier: '$supplier' }, count: { $sum: 1 } } }
    ]);
    res.json({ stats });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
